### ISSUE TITLE
different images, differential content Sync, like casync in managed code

### ISSUE THREAD

**Issue by dorvan** [discimagechef/DiscImageChef#168]
To speed up data management and sync, include something like "systemd/casync" project. To permit image content synchronization related to content and agnostic to Image format. Can be related to synchronize 2 or more active images, committing same actions to all, this Can accelerate adoption of colo-ft/qemu and xen/remus features or permit Fault Tolerant image based synchronization.

**Comment by dorvan** [comment]
I've not used automatic translation. smartphone corrector. Sorry, I've also contacted you many times to collaborate.

**Comment by claunia** [comment]
The corrector definitively did an awful job. If you're the one that tried to contact me on twitter, I answered you but no response. Anyway, it's better if you contact me thru freenode's irc server.

**Comment by darkstar** [comment]
@dorvan I think you to have a protocol(?) or tool(?) to sync *.dicf images between two locations effectively. If so then you seem to have misunderstood the purpose of DiscImageChef. Images in *.dicf format are not meant for live, running systems (say, harddisk backend files for virtual machines) but for archiving purposes.

You might want to take a look at using btrfs with btrfs-send and btrfs-receive, as that can do optimized synchronization between servers, copying only changed data. You might want to disable compression for the *.dicf images then, though...

That being said, the possibility of adding delta-based incremental updates to *.dicf (having a read-only base image and writing all changes to a delta-file, like VMware and others are doing) is very much a possibility in the future...

**Comment by dorvan** [comment]
@claunia ok which channel?

**Comment by darkstar** [comment]
Channel #DiscImageChef on FreeNode
@claunia we should really mention that somewhere in the README ;-)

**Comment by dorvan** [comment]
@darkstar I've understood the DiscImageChef, and it's why I can't use it as it is. The software it's good and it's wrote very well, but I need a different usage for a different use case. The use it's validate data content (files) and data container (image) and using locally or remotely the images as data container and synchronize differential changes verified externally to destination.

**Comment by darkstar** [comment]
@dorvan If I understand you correctly you might be able to do what you want with rsync... It only copies the changed parts of a file, see e.g. [here](https://unix.stackexchange.com/questions/366583/can-rsync-update-a-large-file-that-has-only-changed-partially-without-full-retra). Or you can use btrfs with [btrfs-send and btrfs-receive](https://btrfs.wiki.kernel.org/index.php/Incremental_Backup) that only transfers the changed blocks, thus making transfers very fast.

**Comment by dorvan** [comment]
@darkstar  mind the results of fragmentation and image management (about coherency and dimensions) you have using rsync outside or inside images. We at moment use different methods "like rsync" and "rsync" and like gluster, but we are working on a different approach.

**Comment by dorvan** [comment]
One additional thing for us it's demonstrate coherency and consistency of data across operations. Especially on small systems

**Comment by claunia** [comment]
@dorvan I don't see how your idea fits in the purpose of this application. nonetheless, as it may just be I don't see the great picture, you're still very much welcome to join us in our IRC channel (#discimagechef in freenode) for discussion as well as to create a PR implementing what you are asking for.

**Comment by claunia** [comment]
Closed for lack of information.
