### ISSUE TITLE
Add command-line switch to control whether subchannel data should be read

### ISSUE THREAD

**Issue by SilasLaspada** [discimagechef/DiscImageChef#187]
### Prerequisites

* [X] Are you running the latest version?
* [X] Can you reproduce the problem in the debug version?

### Check and fill as appropiate:
* [X] I was running DiscImageChef under Windows 10...
* [X] ...using .NET Framework 4.7.2...
* [X] ...in 64-bit

### Description

A command-line switch that determines if subchannel data should be read while dumping media would be useful. By default, DIC attempts to read subchannel data if the drive and the output format support it. A command-line switch for the function dump-media would be, in my opinion, the best way to deal with this. There are multiple image formats that support subchannel data, so adding a specific option to each of them would be, as far as I can tell, more difficult to implement.

It would be useful to disable reading subchannel data because it cannot be read consistently, making comparing image files by simply hashing them impossible. This is more useful for testing purposes than archival purposes, but making the testing process easier by removing a few steps would be nice. This can be done in Alcohol 120% by unchecking the "Read Sub-Channel data from current disc" option.

An idea for the command-line switch and description: --subchannel (Default: true) Try to read subchannel data. Only applicable to CD/DDCD/GD.

*Copied from the --lead-in description, I don't know if it only applies to CD/DDCD/GD.

If --subchannel is set to true, DIC should act as it did before. If it is set to false, DIC should not attempt to check for or read subchannel data, and the image dumping process should not be stopped solely because the output format does not support subchannel data. As far as I can tell, no default behavior should have to change for dumping images.

**Comment by claunia** [comment]
Will be added in the future, depends on changing the command line library (current library doesn't handle setting false something that is by default true.

**Comment by SilasLaspada** [comment]
That's odd, --resume is listed as being true by default. Should that switch be removed or marked as not working, or is it handled differently?

**Comment by claunia** [comment]
And does "--resume false" work for you?

**Comment by SilasLaspada** [comment]
Not that I can tell, no. Shouldn't it be at least temporarily removed or give a warning if used? Having a switch that currently does nothing can be confusing.

**Comment by SilasLaspada** [comment]
Is this possible to do now? The command line library has been changed AFAIK, does it support this kind of thing?

**Comment by claunia** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add command line to select subchannel data to dump](https://trello.com/c/9oW4wbMw/22-add-command-line-to-select-subchannel-data-to-dump)

**Comment by claunia** [comment]
Fixed in 470f66ed47aef5d8b99678f5a6efd1eebd416599
