### ISSUE TITLE
Issues with Mode 2+Audio Multi-Track CD-XA

### ISSUE THREAD

**Issue by SilasLaspada** [discimagechef/DiscImageChef#191]
### Prerequisites

* [X] Are you running the latest version?
* [X] Can you reproduce the problem in the debug version?

### Check and fill as appropiate:
* [X] I was running DiscImageChef under Windows 10...
* [X] ...using .NET Framework 4.7.2...
* [X] ...in 64-bit

### Description
Trying to convert a specific MDF/MDS image to BIN/CUE results in an image that ImgBurn says has a larger track 1 than on the disc, as well as a few incorrect sectors. The log file for ImgBurn is attached and the images are being uploaded to dropbox. Dumping the disc as MDF/MDS using DIC seems to work, but I haven't verified that image directly yet, and the converted BIN/CUE has the same issues as the other one.

[ImgBurn.log](https://github.com/claunia/DiscImageChef/files/2239013/ImgBurn.log)

Dropbox link: https://www.dropbox.com/s/ssz1m37mj8yirj6/Monopoly%20Casino.zip?dl=0

**Comment by SilasLaspada** [comment]
There are still issues with this CD, comparing a dump from Alcohol 120% shows that some sectors don't match. "Sector 78717 has different sizes (2048 bytes in image 1, 2328 in image 2) but are otherwise identical
Sector 166669 is different
Sector 166670 is different
Sector 166671 is different" 
Also when I verify the discs, it says that both images have one error and that they have different amounts of unknown sectors.

MDF/MDS: "Checking sector 2560 of 293491, on track 1Uploading statistics
All sector checksums are correct
Total sectors........... 293491
Total errors............ 1
Total unknowns.......... 127168
Total errors+unknowns... 127169"

DICF: "Disc image checksums are correct
All sector checksums are correct
Total sectors........... 293491
Total errors............ 1
Total unknowns.......... 127317
Total errors+unknowns... 127318"

Image files: https://drive.google.com/file/d/1Tz7-KrCPSTWDNFGz5AK_It3MwSC9gEVq/view?usp=sharing

**Comment by claunia** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Converting Alcohol to CDRWin generates incorrect image](https://trello.com/c/NhJ87Syy/21-converting-alcohol-to-cdrwin-generates-incorrect-image)
