### ISSUE TITLE
How to build this for CentOS 7/Red HAT 7/Fedora

### ISSUE THREAD

**Issue by Dimitri2g** [discimagechef/DiscImageChef#204]
Hi,

I am not familiar with build this kind of application and was wondering if you could kindly provide detailed information on how to build this for CentOS7 or Red Hat 7 or Fedora?

Thanks in advance.

-
Dimitri

**Comment by claunia** [comment]
I'm not an user of those distributions but if you install latest mono from:
https://www.mono-project.com/download/stable/#download-lin-centos

including mono, nuget and msbuild.

Then executing `nuget restore` and `msbuild` should suffice.

**Comment by vvs-** [comment]
Fedora 29 (latest) provides only mono 4.8 which is too old for this code, support for mono 5.x is planned in the future for Fedora 31. There is no packages for i686 Fedora 29 on mono-project.com, only x86_64 is provided there. In short: it seems impossible to build this project on 32-bit Fedora.

**Comment by claunia** [comment]
https://fedoraproject.org/wiki/Changes/Mono_5 certainly this project requires mono 5 to work, and will not be backported, sorry.
