### ISSUE TITLE
<ApplicationIdentifier> not detected properly

### ISSUE THREAD

**Issue by mrpijey** [discimagechef/DiscImageChef#215]
### Prerequisites

* [x ] Are you running the latest version?
* [x ] Can you reproduce the problem in the debug version?

### Check and fill as appropiate:
* [x] I was running DiscImageChef under Windows 10.0.17763.292...
* [x ] ...in 64-bit

### Description

The xml sidecar (*.cicm.xml) lacks the proper info in the <ApplicationIdentifier> tag (and possibly more).

Output from *cicm.xml:

              <ApplicationIdentifier>               </ApplicationIdentifier>

Same disc dumped with DIC generates:

Application Identifier: NERO___BURNING_ROM                

### Exact command line used:

DiscImageChef.exe dump-media D: "Disc02_mdf.mds" --first-pregap --force

Both logs from both applications included:

[Disc02_volDesc.txt](https://github.com/discimagechef/DiscImageChef/files/2852792/Disc01_volDesc.txt)
[Disc02_mdf.cicm.xml.txt](https://github.com/discimagechef/DiscImageChef/files/2852793/Disc02_mdf.cicm.xml.txt)

**Comment by claunia** [comment]
Need the image itself
