### ISSUE TITLE
Add support for FATX

### ISSUE THREAD

**Issue by jimmsta** [discimagechef/DiscImageChef#217]
### Description
FATX, used on the original Xbox and Xbox 360 consoles, is practically unsupported everywhere. There are other projects that aren't maintained anymore that offer support for the original Xbox's format - https://github.com/mborgerson/fatx

Ideally, this would be supported for images of original hard drives for archival use. In some cases, users have images of their drives, but no way to pull data out of the image itself. 

The Xbox 360 version of FATX is big-endian encoded as far as I know, and may have additional changes to the format.

**Comment by claunia** [comment]
Detection is already implemented in https://github.com/discimagechef/DiscImageChef/blob/master/DiscImageChef.Filesystems/FATX.cs
