### ISSUE TITLE
[Feature Request] Allow changing the speed of the disc drive

### ISSUE THREAD

**Issue by RibShark** [discimagechef/DiscImageChef#218]
Right now there is no way to change the speed of a given disc drive in DIChef. For some drives/discs, particularly those with ring protections or scratches, a lower read speed may produce better results. Therefore it would be a good idea to implelent this.

**Comment by claunia** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Allow setting the speed of MMC class drives when dumping.](https://trello.com/c/FaWhyV18/14-allow-setting-the-speed-of-mmc-class-drives-when-dumping)
