### ISSUE TITLE
DIC reports different sectors in a DICF image compared with an image converted from it

### ISSUE THREAD

**Issue by SilasLaspada** [discimagechef/DiscImageChef#219]
### Prerequisites

* [X] Are you running the latest version?
* [X] Can you reproduce the problem in the debug version?

### Description
When comparing an image converted from a DICF image, DIC says that some sectors are different. The image I tested ended up having thirteen sectors different according to the compare command after being converted to both MDS and DICF. This doesn't happen when converting from MDS.

### Exact command line used:
`.\DiscImageChef.exe convert-image ".\ROMETWBI.dicf" ".\ROMETWBI.mds" -f`
`.\DiscImageChef.exe compare ".\ROMETWBI.dicf" ".\ROMETWBI.mds"`

### Output of command execution with debug output enabled
`.\DiscImageChef.exe convert-image ".\ROMETWBI.dicf" ".\ROMETWBI.mds" -f`
```
DiscImageChef 4.5.99.1693-00000000 built by DESKTOP-8B4K7NM in Debug
Copyright c 2011-2019 Natalia Portillo

Uploading statistics
Input image format identified by DiscImageChef format.
Output image format: Alcohol 120% Media Descriptor Structure.
Converting media tag CD_FullTOC
335261 sectors to convert
Converting sectors 335261 to 335261 in track 1 (100.00% done)
Converting tag CdSectorSubchannel for sectors 335261 to 335261 in track 1 (100.00% done)
Closing output image.

Conversion done.
```
`.\DiscImageChef.exe compare ".\ROMETWBI.dicf" ".\ROMETWBI.mds"`
```
DiscImageChef 4.5.99.1693-00000000 built by DESKTOP-8B4K7NM in Debug
Copyright c 2011-2019 Natalia Portillo

Input file 1 format identified by DiscImageChef format.
Input file 2 format identified by Alcohol 120% Media Descriptor Structure.
Uploading statistics
Comparing disk image characteristics
Comparing sectors...
Comparing sector 335261 of 335261...
Disc image 1: .\ROMETWBI.dicf
Disc image 2: .\ROMETWBI.mds
Sector 158814 is different
Sector 159089 is different
Sector 159121 is different
Sector 159380 is different
Sector 160449 is different
Sector 160514 is different
Sector 160644 is different
Sector 161781 is different
Sector 176108 is different
Sector 176109 is different
Sector 176376 is different
Sector 176678 is different
Sector 176812 is different
Images differ
```

**Comment by claunia** [comment]
Fixed in e3f958230f456302e8d41d6a7a1763590c3b1399
