### ISSUE TITLE
[Feature Request] Sector/data viewer/exporter for DICF format

### ISSUE THREAD

**Issue by tenyuhuang** [discimagechef/DiscImageChef#224]
### Prerequisites
Running **DiscImageChef 4.5.99.1693-df0b0017**.

### Description
As of now, DICF format supports saving various types of data that would otherwise be unsupported, but Chef doesn't seem to have a functionality for extracting or viewing these data. Being able to view or export them through Chef itself would be handy.

**Comment by claunia** [comment]
@tenyuhuang not exactly why you asked I think but have you tried the printhex command? It spits a hexadecimal print of the chosen sector on console.

**Comment by claunia** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add sector decoder.](https://trello.com/c/ssINmJOi/13-add-sector-decoder)

**Comment by tenyuhuang** [comment]
Thank you very much! I'll check it out asap.
