### ISSUE TITLE
Change wording of DONATIONS / WANTED list to reflect that loaning items are acceptable & that you may pay shipping + small fees.

### ISSUE THREAD

**Issue by ScariLD** [discimagechef/DiscImageChef#232]
Hello Claunia,

Would you please change the wording of the list at https://github.com/discimagechef/DiscImageChef/blob/master/DONATING.md for both hardware and software, to reflect the following:

1. Loaning gear to you is acceptable and appreciated.
2. That you're willing to pay a small fee to cover costs associated with donations & loaners (shipping + misc. fees such as packaging.)

Thank you,

Noah

**Comment by claunia** [comment]
Fixed in a1b80d3f0c03f4be2e24e06dd40b398ee37be696
