### ISSUE TITLE
ASAP: Update WANTED / DONATION list to reflect current inventory + needs

### ISSUE THREAD

**Issue by ScariLD** [discimagechef/DiscImageChef#233]
Hello Claunia,

Would you be able to update the list currently at https://github.com/discimagechef/DiscImageChef/blob/master/DONATING.md to reflect the actual state of what drives and software you currently need? This will be helpful as the list is being viewed by institutions that will be packaging and searching their catalogs for the drives you are requesting.

Thank you,

Noah

**Comment by claunia** [comment]
Fixed in 52dd769cb37fd08d3da34f960675742a6ac8e3cb.
