### ISSUE TITLE
Add a "Drive Media" section to DONATIONS / WANTED list

### ISSUE THREAD

**Issue by ScariLD** [discimagechef/DiscImageChef#234]
Hello Claunia,

Would you be able to add a section to the list currently at https://github.com/discimagechef/DiscImageChef/blob/master/DONATING.md to reflect the actual media (disks, discs, and or cables) you need for any given type of drive? If it's generic or you already have it, please ignore that item, but this is a need due to institutions having the actual read / write hardware, but no media.

Thank you,

Noah

**Comment by claunia** [comment]
Fixed in a1b80d3f0c03f4be2e24e06dd40b398ee37be696
