### ISSUE TITLE
No usable version of the libssl was found

### ISSUE THREAD

**Issue by FakeShemp** [discimagechef/DiscImageChef#238]
### Prerequisites

* [X] Are you running the latest version?
* [X] Can you reproduce the problem in the debug version?

### Check and fill as appropiate:
* [ ] I was running DiscImageChef under Windows [version here]...
* [X] I was running DiscImageChef under Linux [Ubuntu 19.04]...
* [ ] I was running DiscImageChef under FreeBSD [version here]...
* [ ] I was running DiscImageChef under macOS [version here]...
* [ ] ...using .NET Framework [version here]...
* [X] ...using .NET Core [3.0.100]...
* [X] ...using Mono [5.18.0.240]...
* [ ] ...in 32-bit
* [X] ...in 64-bit

### Description

Program complains that there is "No usable version of the libssl was found"

### Exact command line used:

`./DiscImageChef analyze disc.cue`

### Expected behavior:
Disc image to be analyzed

### Actual behavior:
```
DiscImageChef 4.5.99.1693-f0897168 built by rebecca-H67MA-UD2H-B3 in Debug
Copyright © 2011-2019 Natalia Portillo

No usable version of the libssl was found
Aborted (core dumped)
```

### If command was expected to work with a device fill this:

* **Manufacturer**:
* **Model**:
* **Bus**:
    * [ ] Parallel ATA
    * [ ] Serial ATA
    * [ ] SCSI (any)
    * [ ] ATAPI (mark above if parallel or serial)
    * [ ] USB
    * [ ] FireWire
    * [ ] PCMCIA
    * [ ] SecureDigital
    * [ ] MultiMediaCard
    
### Output of command execution with debug output enabled
```
DiscImageChef 4.5.99.1693-f0897168 built by rebecca-H67MA-UD2H-B3 in Debug
Copyright © 2011-2019 Natalia Portillo

No usable version of the libssl was found
Aborted (core dumped)
```

**Comment by claunia** [comment]
Upstream in https://github.com/dotnet/coreclr/issues/24757

As a temporary workaround installing libssl1.0 fixes it.

For example in Ubuntu:
```
wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl1.0/libssl1.0.0_1.0.2n-1ubuntu6_amd64.deb
sudo dpkg -i libssl1.0.0_1.0.2n-1ubuntu6_amd64.deb
```

**Comment by robin-francois** [comment]
Apparently, on Ubuntu 23.04, the workaround might have changed a bit (I am reporting this based on a third party informing me, so untested by me). This workaround could also be necessary to install the Aaru deb package:
```
wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl1.0/libssl1.0.0_1.0.2n-1ubuntu5_amd64.deb
sudo dpkg -i libssl1.0.0_1.0.2n-1ubuntu5_amd64.deb
``` 
 
And another dependency needs to be installed so that Ubuntu can be : 
```
wget https://ftp.fau.de/ubuntu/pool/main/i/icu/libicu70_70.1-2_amd64.deb
sudo dpkg -i libicu70_70.1-2_amd64.deb```
