### ISSUE TITLE
Dumping to image formats with two image files doesn't write data to the descriptor file

### ISSUE THREAD

**Issue by SilasLaspada** [discimagechef/DiscImageChef#252]
### Prerequisites

* [X] Are you running the latest version?
* [X] Can you reproduce the problem in the debug version?

### Description

Dumping to an image format that uses two image files (BIN/CUE, MDF/MDS, and IMG/CCD have been tested) results in the descriptor file being 0 bytes. Checked on two different computers with two different drives, as well as different CDs.

Example images:
[Sony USB Driver (CUE).zip](https://github.com/discimagechef/DiscImageChef/files/3878144/Sony.USB.Driver.CUE.zip)
[Sony USB Driver (MDS).zip](https://github.com/discimagechef/DiscImageChef/files/3878147/Sony.USB.Driver.MDS.zip)
[Sony USB Driver (CCD).zip](https://github.com/discimagechef/DiscImageChef/files/3878148/Sony.USB.Driver.CCD.zip)

**Comment by claunia** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Image sidecars are not written correctly](https://trello.com/c/OxUddiJk/7-image-sidecars-are-not-written-correctly)

**Comment by claunia** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Overflow when dumping XGD in TS-H352 Kreon under Windows](https://trello.com/c/9UAHpJ8I/8-overflow-when-dumping-xgd-in-ts-h352-kreon-under-windows)

**Comment by claunia** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Overflow when dumping XGD in TS-H352 Kreon under Windows](https://trello.com/c/9UAHpJ8I/8-overflow-when-dumping-xgd-in-ts-h352-kreon-under-windows)

**Comment by SilasLaspada** [comment]
Fixed at some point during the CD dump rewrite. Tested with CUE, MDS, and CCD.
