### ISSUE TITLE
Does not work with Daemon Tools drives

### ISSUE THREAD

**Issue by aybe** [discimagechef/DiscImageChef#271]
### Prerequisites
- [x] Are you running the latest version?

### Check and fill as appropriate:
* [x] I was running DiscImageChef under Windows [10]...

### Exact command line used:

`DiscImageChef dump-media --device \\?\G: -o out.bin`

### Actual behavior:
```
DiscImageChef 4.5.1.1692-1930cf95 built by dicbuilder in Release
Copyright c 2011-2018 Natalia Portillo

InstanceId: ROOT\SCSIADAPTER\0000
No plugin supports requested extension.
```
    
### Output of command execution with debug output enabled
```
DiscImageChef 4.5.1.1692-1930cf95 built by dicbuilder in Release
Copyright c 2011-2018 Natalia Portillo

DEBUG (Dump-Media command): --debug=True
DEBUG (Dump-Media command): --verbose=False
DEBUG (Dump-Media command): --device=\\?\G:
DEBUG (Dump-Media command): --stop-on-error=False
DEBUG (Dump-Media command): --force=False
DEBUG (Dump-Media command): --retry-passes=5
DEBUG (Dump-Media command): --persistent=False
DEBUG (Dump-Media command): --resume=True
DEBUG (Dump-Media command): --lead-in=False
DEBUG (Dump-Media command): --encoding=
DEBUG (Dump-Media command): --output=out.bin
DEBUG (Dump-Media command): --format=
DEBUG (Dump-Media command): --force=False
DEBUG (Dump-Media command): --options=
DEBUG (Dump-Media command): --cicm-xml=
DEBUG (Dump-Media command): --skip=512
DEBUG (Dump-Media command): --no-metadata=False
DEBUG (Dump-Media command): Parsed options:
DEBUG (Windows devices): NT device path: \\?\scsi#disk&ven_st3000dm&prod_001-1er166#4&239d8b02&0&030000#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}
InstanceId: ROOT\SCSIADAPTER\0000
No plugin supports requested extension.
```

**Comment by claunia** [comment]
@aybe can you confirm G: is a Daemon Tools virtual drive?

**Comment by aybe** [comment]
Yes it is a DT drive:

![DTLite_2020-02-02_16-40-19](https://user-images.githubusercontent.com/1537591/73610705-b6c87900-45da-11ea-9dc4-abdfcdc364f2.png)

**Comment by claunia** [comment]
Using virtual drives as devices is not supported and won't be supported. There is no reason to use them with DiscImageChef.

**Comment by aybe** [comment]
So you are suggesting to work against the image file directly ?

**Comment by claunia** [comment]
Basically that's what it is what this software is designed to do.

**Comment by aybe** [comment]
Alright, I'll do that then, thank you for the quick support !

**Comment by claunia** [comment]
No problem. You can also find us in our IRC and Discord channels for help from me and other users.

**Comment by aybe** [comment]
Okay, thank you :)

PS I think I just found a bug when you run the tool from another directory, going to open another issue.
